//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevelopmentChallenge.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Shapes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shapes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevelopmentChallenge.Data.Resources.Shapes", typeof(Shapes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Círculos.
        /// </summary>
        public static string Circulo_NombrePlural {
            get {
                return ResourceManager.GetString("Circulo_NombrePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Círculo.
        /// </summary>
        public static string Circulo_NombreSingular {
            get {
                return ResourceManager.GetString("Circulo_NombreSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuadrados.
        /// </summary>
        public static string Cuadrado_NombrePlural {
            get {
                return ResourceManager.GetString("Cuadrado_NombrePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuadrado.
        /// </summary>
        public static string Cuadrado_NombreSingular {
            get {
                return ResourceManager.GetString("Cuadrado_NombreSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista vacía de formas!.
        /// </summary>
        public static string Empty_List {
            get {
                return ResourceManager.GetString("Empty_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to formas.
        /// </summary>
        public static string Formas_NombresPlural {
            get {
                return ResourceManager.GetString("Formas_NombresPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forma.
        /// </summary>
        public static string Formas_NombresSingular {
            get {
                return ResourceManager.GetString("Formas_NombresSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte de Formas.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perimetro.
        /// </summary>
        public static string Perimetro {
            get {
                return ResourceManager.GetString("Perimetro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangulos.
        /// </summary>
        public static string Rectangulo_NombrePlural {
            get {
                return ResourceManager.GetString("Rectangulo_NombrePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rentangulo.
        /// </summary>
        public static string Rectangulo_NombreSingular {
            get {
                return ResourceManager.GetString("Rectangulo_NombreSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trapecios.
        /// </summary>
        public static string Trapecio_NombrePlural {
            get {
                return ResourceManager.GetString("Trapecio_NombrePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trapecio.
        /// </summary>
        public static string Trapecio_NombreSingular {
            get {
                return ResourceManager.GetString("Trapecio_NombreSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triángulos.
        /// </summary>
        public static string Triangulo_NombrePlural {
            get {
                return ResourceManager.GetString("Triangulo_NombrePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triángulo.
        /// </summary>
        public static string Triangulo_NombreSingular {
            get {
                return ResourceManager.GetString("Triangulo_NombreSingular", resourceCulture);
            }
        }
    }
}
